    # shared data
    - DJANGO_STATIC_ROOT=/data/static
    - DJANGO_MEDIA_ROOT=/data/media
    - DJANGO_PRIVATE_MEDIA_ROOT=/data/private_media
    - DJANGO_RESULT_MEDIA_ROOT=/results

    # allow better logging with docker
    - PYTHONIOENCODING=utf-8
    - PYTHONUNBUFFERED=non-empty-string

    - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
    - DJANGO_DATABASE_URL=postgis://postgres@database/postgres
    - DJANGO_EMAIL_HOST=localhost

    # Settings above only need to be changed when not running in
    # osmaxx's docker environment
    ##########################################################################
{% if email %}
    # EMAIL
    - DJANGO_EMAIL_BACKEND={{ DJANGO_EMAIL_BACKEND }}
    - DJANGO_EMAIL_HOST={{ DJANGO_EMAIL_HOST }}
    - DJANGO_EMAIL_HOST_PASSWORD={{ DJANGO_EMAIL_HOST_PASSWORD }}
    - DJANGO_EMAIL_HOST_USER={{ DJANGO_EMAIL_HOST_USER }}
    - DJANGO_EMAIL_PORT={{ DJANGO_EMAIL_PORT }}
    - DJANGO_EMAIL_USE_TLS={{ DJANGO_EMAIL_USE_TLS }}
    - DJANGO_EMAIL_USE_SSL={{ DJANGO_EMAIL_USE_SSL }}
    - DJANGO_DEFAULT_FROM_EMAIL={{ DJANGO_DEFAULT_FROM_EMAIL }}
    - DJANGO_SERVER_EMAIL={{ DJANGO_SERVER_EMAIL }}
{% endif %}
    # port and host application listens
    - APP_PORT={{ APP_PORT }}
    - APP_HOST={{ APP_HOST }}
    # Logging
    - DJANGO_LOG_LEVEL={{ DJANGO_LOG_LEVEL }}
    - DJANGO_SECRET_KEY={{ DJANGO_SECRET_KEY }}
    - DJANGO_X_FRAME_OPTIONS='SAMEORIGIN'
{% if production %}
    # GENERAL SECURITY
    - DJANGO_ALLOWED_HOSTS={{ DJANGO_ALLOWED_HOSTS }}
    - DJANGO_SECURE_CONTENT_TYPE_NOSNIFF=true
    - DJANGO_SECURE_BROWSER_XSS_FILTER=true
    - DJANGO_SESSION_COOKIE_HTTPONLY=true
    - DJANGO_CSRF_COOKIE_HTTPONLY=false
  {% if ssl %}
    # SSL IS ON
    - DJANGO_SECURE_HSTS_SECONDS={{ DJANGO_SECURE_HSTS_SECONDS }}
    - DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS={{ DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS }}
    - DJANGO_SECURE_SSL_REDIRECT=true
    - DJANGO_SECURE_SSL_HOST={{ DJANGO_SECURE_SSL_HOST }}
    - DJANGO_SECURE_REDIRECT_EXEMPT=
    - DJANGO_SESSION_COOKIE_SECURE=true
    - DJANGO_CSRF_COOKIE_SECURE=true
  {% else %}
    # SSL IS OFF
    - DJANGO_SECURE_HSTS_SECONDS=
    - DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=
    - DJANGO_SECURE_SSL_REDIRECT=false
    - DJANGO_SECURE_SSL_HOST=
    - DJANGO_SECURE_REDIRECT_EXEMPT=
    - DJANGO_SESSION_COOKIE_SECURE=false
    - DJANGO_CSRF_COOKIE_SECURE=false
  {% endif %}
{% endif %}