language: python

cache: pip

sudo: false

env:
    - TOX_ENV='py35-django{1.9}-drf{3.3}'  # Django supports py 3.5 only since 1.8

matrix:
  fast_finish: true

services:
  - docker

before_install:
  - docker pull geometalab/postgis-with-translit
  - docker run -d -p "127.0.0.1:54321:5432" -e POSTGRES_DB='postgres' --name pg_tests geometalab/postgis-with-translit
  - docker ps -a
  - sleep 10

install:
  - pip install detox

script:
    - detox -e $TOX_ENV
