language: python

cache: pip

sudo: false

env:
    - TOX_ENV=py34-flake8
    - TOX_ENV=py34-django1.8-drf3.2
    - TOX_ENV=py34-django1.9-drf3.2
    - TOX_ENV=py34-django1.8-drf3.3
    - TOX_ENV=py34-django1.9-drf3.3
    - TOX_ENV=py34-slow-tests
    - TOX_ENV=py35-flake8
    - TOX_ENV=py35-django1.8-drf3.2
    - TOX_ENV=py35-django1.9-drf3.2
    - TOX_ENV=py35-django1.8-drf3.3
    - TOX_ENV=py35-django1.9-drf3.3
    - TOX_ENV=py35-slow-tests

matrix:
  fast_finish: true

services:
  - docker

before_install:
  - docker pull geometalab/postgis-with-translit
  - docker run -d -p "127.0.0.1:54321:5432" -e POSTGRES_DB='postgres' --name pg_tests geometalab/postgis-with-translit
  - docker ps -a
  - sleep 10

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
