# TODO: this file is only a placeholder for now!
osmaxxwebapp:
    extends:
        file: compose-common.yml
        service: osmaxx
    ports:
        - "8000:8000"
    command: honcho start -f Procfile.django
    links:
        - osmaxxrabbitmq:rabbit
        - osmaxxdatabase

osmaxxrabbitmq:
    extends:
        file: compose-common.yml
        service: osmaxxrabbitmq

osmaxxcelery:
    extends:
        file: compose-common.yml
        service: osmaxx
    command: honcho start -f Procfile.celery
    links:
        - osmaxxrabbitmq:rabbit
        - osmaxxdatabase

osmaxxdatabase:
    extends:
        file: compose-common.yml
        service: osmaxxdatabase
