osmaxxshareddata:
  image: buildpack-deps:jessie
  command: /bin/true
  volumes:
    - /data

# TODO: this file is only a placeholder for now!
osmaxxwebapp:
  extends:
    file: compose-common.yml
    service: osmaxxbase
  ports:
    - "8000:8000"
  volumes_from:
    - osmaxxshareddata
  command: honcho start -f Procfile.django
  links:
    - osmaxxrabbitmq:rabbit
    - osmaxxdatabase
    - osmaxxemail
    - osmaxxcelery
  environment:
    - APP_PORT=8000
    - APP_HOST=0.0.0.0
    - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
    - DJANGO_DATABASE_URL=postgis://postgres@osmaxxdatabase/postgres
    - DJANGO_EMAIL_USE_TLS=false
    - DJANGO_EMAIL_HOST=osmaxxemail
    - DJANGO_EMAIL_HOST_PASSWORD=osmaxx
    - DJANGO_EMAIL_HOST_USERNAME=osmaxx
    - DJANGO_EMAIL_PORT=25

osmaxxrabbitmq:
  extends:
    file: compose-common.yml
    service: osmaxxrabbitmqbase

osmaxxcelery:
  extends:
    file: compose-common.yml
    service: osmaxxbase
  volumes_from:
    - osmaxxshareddata
  command: honcho start -f Procfile.celery
  links:
    - osmaxxrabbitmq:rabbit
    - osmaxxdatabase
    - osmaxxemail
  environment:
    - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
    - DJANGO_DATABASE_URL=postgis://postgres@osmaxxdatabase/postgres

osmaxxdatabase:
  extends:
    file: compose-common.yml
    service: osmaxxdatabasebase

osmaxxemail:
  image: catatnight/postfix
  environment:
    - maildomain=osmaxx.hsr.ch
    - smtp_user=osmaxx:osmaxx
  expose:
    - 25
