shareddatadev:
  image: buildpack-deps:jessie
  command: /bin/true
  volumes:
    # as noted in https://docs.docker.com/userguide/dockervolumes/#mount-a-host-file-as-a-data-volume
    # the parent directory should be mounted, not the directories itself
    # otherwise we get OSError: Device or resource busy
    - /data
    # database
    - /database/data
    # temporary results directory used as pipe between multiple docker forests
    - /tmp/osmaxx-results:/results
    # emails file from email sending during development and testing
    - /tmp/osmaxx-development-emails:/dev-emails
  net: "none"

sourcedev:
  build: docker/volume-mount
  volumes:
    - ./osmaxx-py:/home/osmaxx/source

webappdev:
  extends:
    file: compose-common.yml
    service: base
  command: honcho start -f Procfile.django.dev
  ports:
    - "8000:8000"
  expose:
    - "8000"
  volumes_from:
    - sourcedev
    - shareddatadev
  links:
    - rabbitmqdev:rabbit
    - databasedev:database
    - celerydev:celery
  external_links:
    - osmaxxpostgisconversion_api_1:conversion_service
  environment:
    - DJANGO_SETTINGS_MODULE=config.settings.local
    - DJANGO_DEBUG=true
    - DJANGO_DEFAULT_FROM_EMAIL=no-reply@osmaxx.dev
    - DJANGO_SERVER_EMAIL=no-reply@osmaxx.dev
    - DJANGO_EMAIL_FILE_PATH=/dev-emails
    - DJANGO_EMAIL_BACKEND=django.core.mail.backends.filebased.EmailBackend
    - DJANGO_SECRET_KEY=my.secret.key.is.not.secret!
    - DJANGO_OSMAXX_CONVERSION_SERVICE_API_URL=http://conversion_service:8901/api/

celerydev:
  extends:
    file: compose-common.yml
    service: base
  command: honcho start -f Procfile.celery
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - sourcedev
    - shareddatadev
  links:
    - rabbitmqdev:rabbit
    - databasedev:database
  environment:
    - DJANGO_SETTINGS_MODULE=config.settings.local
    - DJANGO_DEBUG=true
    - DJANGO_DEFAULT_FROM_EMAIL=no-reply@osmaxx.dev
    - DJANGO_SERVER_EMAIL=no-reply@osmaxx.dev
    - DJANGO_EMAIL_FILE_PATH=/dev-emails
    - DJANGO_EMAIL_BACKEND=django.core.mail.backends.filebased.EmailBackend
    - DJANGO_SECRET_KEY=my.secret.key.is.not.secret!

rabbitmqdev:
  extends:
    file: compose-common.yml
    service: rabbitmqbase

databasedev:
  extends:
    file: compose-common.yml
    service: databasebase
  volumes_from:
    - shareddatadev
  environment:
    - PGDATA=/database/data
