databasebase:
  image: geometalab/postgis:9.4

base:
  build: .
  environment:
    # shared data
    - DJANGO_STATIC_ROOT=/data/static
    - DJANGO_MEDIA_ROOT=/data/media
    - DJANGO_PRIVATE_MEDIA_ROOT=/data/private_media
    - DJANGO_RESULT_MEDIA_ROOT=/results
    # --link some-rabbit:rabbit "just works"
    - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
    - DJANGO_DATABASE_URL=postgis://postgres@database/postgres
    - DJANGO_EMAIL_HOST=localhost
    # Settings above likely need to be changed, depending on  the environment
    ##########################################################################
    # WARNING: restarting the server changes the secret key and thus loggs out
    # other users.
    - DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
    # EMAIL
    - DJANGO_DEFAULT_FROM_EMAIL='noreply osmaxx <noreply@osmaxx.hsr.ch>'

    # Logging
    - DJANGO_LOG_LEVEL=ERROR

    # SECURITY
    - DJANGO_ALLOWED_HOSTS=.osmaxx.hsr.ch.

    # SSL
    # set this to 60 seconds and then to 518400 when you can prove it works
    - DJANGO_SECURE_HSTS_SECONDS=60
    - DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=true
    - DJANGO_SECURE_SSL_REDIRECT=true
    - DJANGO_SECURE_SSL_HOST='osmaxx.hsr.ch'
    - DJANGO_SECURE_REDIRECT_EXEMPT=

    # OTHER SECURITY SETTINGS
    - DJANGO_SECURE_CONTENT_TYPE_NOSNIFF=true
    - DJANGO_SECURE_BROWSER_XSS_FILTER=true
    - DJANGO_SESSION_COOKIE_SECURE=true
    - DJANGO_SESSION_COOKIE_HTTPONLY=true
    - DJANGO_CSRF_COOKIE_SECURE=true
    - DJANGO_CSRF_COOKIE_HTTPONLY=true
    - DJANGO_X_FRAME_OPTIONS='DENY'

rabbitmqbase:
  image: rabbitmq:3
