# INFO: remember to update the setup.production.sh if you change something here.

shareddata:
  image: buildpack-deps:jessie
  command: /bin/true
  volumes:
    - /data
    - /database/data
    - /tmp/osmaxx-results:/results
  net: "none"

webapp:
  extends:
    file: compose-common.yml
    service: base
  ports:
    - "8000:8000"
  volumes_from:
    - shareddata
  command: honcho start -f Procfile.django
  links:
    - rabbitmq:rabbit
    - database
    - celery
  environment:
    - APP_PORT=8000
    - APP_HOST=0.0.0.0
    - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
    - DJANGO_DATABASE_URL=postgis://postgres@database/postgres
    - DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
    # set to true, if ssl is enabled
    - DJANGO_SECURE_SSL_REDIRECT=false
    - DJANGO_CSRF_COOKIE_SECURE=false
    - DJANGO_CSRF_COOKIE_HTTPONLY=false
    - PYTHONIOENCODING=utf-8
    - PYTHONUNBUFFERED=non-empty-string
    - DJANGO_ALLOWED_HOSTS=your.host.example
    - DJANGO_LOG_LEVEL=ERROR

rabbitmq:
  extends:
    file: compose-common.yml
    service: rabbitmqbase

celery:
  extends:
    file: compose-common.yml
    service: base
  command: honcho start -f Procfile.celery
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - shareddata
  links:
    - rabbitmq:rabbit
    - database
  environment:
    - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
    - DJANGO_DATABASE_URL=postgis://postgres@database/postgres
    - DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
    - PYTHONIOENCODING=utf-8
    - PYTHONUNBUFFERED=non-empty-string
    - DJANGO_LOG_LEVEL=ERROR

database:
  extends:
    file: compose-common.yml
    service: databasebase
  volumes_from:
    - shareddata
  environment:
    - PGDATA=/database/data
