# INFO: remember to update the setup.production.sh if you change something here.

shareddata:
  image: buildpack-deps:jessie
  command: /bin/true
  volumes:
    - /data
    - /database/data
    - /tmp/osmaxx-results:/results
  net: "none"

webapp:
  extends:
    file: compose-common.yml
    service: base
  ports:
    - "8000:8000"
  volumes_from:
    - shareddata
  command: honcho start -f Procfile.django
  links:
    - rabbitmq:rabbit
    - database
    - celery
  environment:
    # THIS MUST BE SET TO A SECRET KEY!
    - DJANGO_SECRET_KEY=
    # comma separated list, no brackets, e.g. localhost,dev.myhost.com
    - DJANGO_ALLOWED_HOSTS=
    # theses settings should be adapted before deploying
    - DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
    - DJANGO_EMAIL_HOST=
    - DJANGO_EMAIL_HOST_PASSWORD=
    - DJANGO_EMAIL_HOST_USER=
    - DJANGO_EMAIL_PORT=
    - DJANGO_EMAIL_USE_TLS=
    - DJANGO_EMAIL_USE_SSL=
    - DJANGO_DEFAULT_FROM_EMAIL=
    - DJANGO_SERVER_EMAIL=
    # if SSL is ON: unomment
#    - DJANGO_CSRF_COOKIE_SECURE=true
#    - DJANGO_SESSION_COOKIE_SECURE=true

    ######### these should not require any change
    - DJANGO_SETTINGS_MODULE=config.settings.production
    - DJANGO_DEBUG=false



rabbitmq:
  extends:
    file: compose-common.yml
    service: rabbitmqbase

celery:
  extends:
    file: compose-common.yml
    service: base
  command: honcho start -f Procfile.celery
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - shareddata
  links:
    - rabbitmq:rabbit
    - database
  environment:
    # THIS MUST BE SET TO A SECRET KEY!
    - DJANGO_SECRET_KEY=
    # comma separated list, no brackets, e.g. localhost,dev.myhost.com
    - DJANGO_ALLOWED_HOSTS=
    # theses settings should be adapted before deploying
    - DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
    - DJANGO_EMAIL_HOST=
    - DJANGO_EMAIL_HOST_PASSWORD=
    - DJANGO_EMAIL_HOST_USER=
    - DJANGO_EMAIL_PORT=
    - DJANGO_EMAIL_USE_TLS=
    - DJANGO_EMAIL_USE_SSL=
    - DJANGO_DEFAULT_FROM_EMAIL=
    - DJANGO_SERVER_EMAIL=
    # if SSL is ON: unomment
#    - DJANGO_CSRF_COOKIE_SECURE=true
#    - DJANGO_SESSION_COOKIE_SECURE=true

    ######### these should not require any change
    - DJANGO_SETTINGS_MODULE=config.settings.production
    - DJANGO_DEBUG=false

database:
  extends:
    file: compose-common.yml
    service: databasebase
  volumes_from:
    - shareddata
  environment:
    - PGDATA=/database/data
