databasebase:
  image: geometalab/postgis:9.4

base:
  build: .
  environment:
    # shared data
    - DJANGO_STATIC_ROOT=/data/static
    - DJANGO_MEDIA_ROOT=/data/media
    - DJANGO_PRIVATE_MEDIA_ROOT=/data/private_media
    - DJANGO_RESULT_MEDIA_ROOT=/results
    # --link some-rabbit:rabbit "just works"
    - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
    - DJANGO_DATABASE_URL=postgis://postgres@database/postgres

    # Logging
    - PYTHONUNBUFFERED=non-empty-string
    - PYTHONIOENCODING=utf-8
    - DJANGO_LOG_LEVEL=INFO
    
    # We enable Python hash randomization to protect Django from certain DoS attacks.
    # See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/#python-options
    - PYTHONHASHSEED=random

    # Settings above only need to be changed, if docker-compose is being changed
    # or not used at all.

    ##########################################################################

    # port and host application listens
    - APP_PORT=8000
    - APP_HOST=0.0.0.0

    # hardened security compared to default settings.
    - DJANGO_SECURE_BROWSER_XSS_FILTER=true
    - DJANGO_SECURE_CONTENT_TYPE_NOSNIFF=true

rabbitmqbase:
  image: rabbitmq:3
