shareddata:
  image: buildpack-deps:jessie
  command: /bin/true
  volumes:
    - /data
    - /database/data
    - /tmp/osmaxx-results:/results
  net: "none"

webapp:
  extends:
    file: compose-common.yml
    service: base
  ports:
    - "8000:8000"
  volumes_from:
    - shareddata
  command: honcho start -f Procfile.django
  links:
    - rabbitmq:rabbit
    - database
    - email
    - celery
  environment:
    - APP_PORT=8000
    - APP_HOST=0.0.0.0
    - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
    - DJANGO_DATABASE_URL=postgis://postgres@database/postgres
    - DJANGO_EMAIL_USE_TLS=false
    - DJANGO_EMAIL_HOST=email
    - DJANGO_EMAIL_HOST_PASSWORD=osmaxx
    - DJANGO_EMAIL_HOST_USERNAME=osmaxx
    - DJANGO_EMAIL_PORT=25

rabbitmq:
  extends:
    file: compose-common.yml
    service: rabbitmqbase

celery:
  extends:
    file: compose-common.yml
    service: base
  command: honcho start -f Procfile.celery
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - shareddata
  links:
    - rabbitmq:rabbit
    - database
    - email
  environment:
    - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
    - DJANGO_DATABASE_URL=postgis://postgres@database/postgres
    - DJANGO_EMAIL_HOST=email

database:
  extends:
    file: compose-common.yml
    service: databasebase
  volumes_from:
    - shareddata
  environment:
    - PGDATA=/database/data

email:
  image: catatnight/postfix
  environment:
    - maildomain=.hsr.ch
    - smtp_user=osmaxx:osmaxx
  expose:
    - 25
