osmaxxdatabase:
    build: docker/postgis

osmaxx:
    build: .
    environment:
        # --link some-rabbit:rabbit "just works"
        - DJANGO_CELERY_BROKER_URL=amqp://guest@rabbit
        - DJANGO_DATABASE_URL=postgis://postgres@database/postgres

osmaxxrabbitmq:
    image: rabbitmq:3
