source:
    build: docker/source
# until https://github.com/docker/docker/pull/12648 is resolved, we can't use
# user namespaces properly
#    user: osmaxx
    volumes:
        - osmaxx:/home/osmaxx/source

static:
    build: docker/webapp
    command: python manage.py collectstatic --noinput
    volumes:
        - static:/home/osmaxx/static
    volumes_from:
        - source

media:
    build: docker/webapp
    command: echo "done"
    volumes:
        - private_media:/home/osmaxx/private_media
        - media:/home/osmaxx/media
    volumes_from:
        - source

database:
    build: docker/database

webapp:
    build: docker/webapp
    # on production, enable the following
    # command: gunicorn -b 0.0.0.0:8000 wsgi:application
    command: python manage.py runserver 0.0.0.0:8000
    volumes_from:
        - source
        - static
        - media
    links:
        - database
    ports:
        - "8000:8000"

rabbitmq:
    image: rabbitmq:3

celery:
    build: docker/celery
    command: celery -A config worker -l info
    links:
        - rabbitmq:rabbit
    volumes_from:
        - source
#    environment:
#        - DJANGO_SETTINGS_MODULE='config.settings.production'

# webserver:
#     build: webserver
#     ports:
#         - "80:80"
#         - "443:443"
#     links:
#         - webapp
